In [1]:
import pandas as pd

In [2]:
dataset = pd.DataFrame({"Size":["s","m","l","xl","s","m","l","s","s","l","xl","m"]})
dataset.head(3)

  Size
0    s
1    m
2    l

In [3]:
ord_data = [["s","m","l","xl"]]

In [4]:
from sklearn.preprocessing import OrdinalEncoder

In [5]:
oe = OrdinalEncoder(categories=ord_data)
oe.fit(dataset[["Size"]])

OrdinalEncoder(categories=[['s', 'm', 'l', 'xl']])

In [6]:
dataset["size_en"]=oe.transform(dataset[["Size"]])

In [7]:
dataset

   Size  size_en
0     s      0.0
1     m      1.0
2     l      2.0
3    xl      3.0
4     s      0.0
5     m      1.0
6     l      2.0
7     s      0.0
8     s      0.0
9     l      2.0
10   xl      3.0
11    m      1.0

In [19]:
ord_data1 ={"s":9 , "m":8 , "l":7 , "xl":6} #create a dictionary

In [20]:
dataset["size_en_map3"] = dataset["Size"].map(ord_data1) #Use the map function to map the size to the corresponding ordinal value

In [21]:
dataset

   Size  size_en  size_en_map  size_en_map2  size_en_map3
0     s      0.0            0             0             9
1     m      1.0            1             1             8
2     l      2.0            2             2             7
3    xl      3.0            3             3             6
4     s      0.0            0             0             9
5     m      1.0            1             1             8
6     l      2.0            2             2             7
7     s      0.0            0             0             9
8     s      0.0            0             0             9
9     l      2.0            2             2             7
10   xl      3.0            3             3             6
11    m      1.0            1             1             8

In [22]:
data = pd.read_csv("Bank_data.csv")

In [23]:
data.head()

,loan_id,married,gender,dependency,Self_Employee,Applicant,coapplicant,Loan_amount,creadit_his,propert,loan_status
0,LN1000,Yes,Female,0,Yes,17154.0,13688.0,133487.0,0.0,Rural,Rejected
1,LN1001,Yes,Male,0,Yes,NaN,2995.0,50849.0,1.0,Urban,Rejected
2,LN1002,Yes,Male,1,No,21923.0,3046.0,85520.0,0.0,Semiurban,Rejected
3,LN1003,NaN,Female,3+,No,19718.0,14947.0,NaN,1.0,Rural,Rejected
4,LN1004,Yes,Female,3+,Yes,9636.0,319.0,299794.0,0.0,Rural,Rejected

In [24]:
data["propert"].fillna(data["propert"].mode()[0],inplace=True)

C:\Users\lenovo\anaconda3\ipykernel_10236\2706319778.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["propert"].fillna(data["propert"].mode()[0],inplace=True)

In [25]:
data

,loan_id,married,gender,dependency,Self_Employee,Applicant,coapplicant,Loan_amount,creadit_his,propert,loan_status
0,LN1000,Yes,Female,0,Yes,17154.0,13688.0,133487.0,0.0,Rural,Rejected
1,LN1001,Yes,Male,0,Yes,NaN,2995.0,50849.0,1.0,Urban,Rejected
2,LN1002,Yes,Male,1,No,21923.0,3046.0,85520.0,0.0,Semiurban,Rejected
3,LN1003,NaN,Female,3+,No,19718.0,14947.0,NaN,1.0,Rural,Rejected
4,LN1004,Yes,Female,3+,Yes,9636.0,319.0,299794.0,0.0,Rural,Rejected
...,...,...,...,...,...,...,...,...,...,...,...
613,LN1613,No,Female,2,Yes,4372.0,11822.0,86905.0,0.0,Urban,Approved
614,LN1614,No,Female,2,Yes,3614.0,6723.0,132014.0,1.0,Semiurban,Rejected
615,LN1615,Yes,Male,1,Yes,14451.0,12379.0,439022.0,1.0,Rural,Rejected
616,LN1616,No,Female,1,No,15067.0,3499.0,169017.0,0.0,Semiurban,Approved
617,LN1617,No,Female,2,No,7912.0,10428.0,379816.0,1.0,Rural,Rejected

In [27]:
en_ord_data = [["Rural" , "Urban" , "Semiurban"]]

In [28]:
from sklearn.preprocessing import OrdinalEncoder

In [33]:
oen = OrdinalEncoder(categories=en_ord_data)
data["propert"] = oen.fit_transform(data[["propert"]])

In [34]:
data

,loan_id,married,gender,dependency,Self_Employee,Applicant,coapplicant,Loan_amount,creadit_his,propert,loan_status
0,LN1000,Yes,Female,0,Yes,17154.0,13688.0,133487.0,0.0,0.0,Rejected
1,LN1001,Yes,Male,0,Yes,NaN,2995.0,50849.0,1.0,1.0,Rejected
2,LN1002,Yes,Male,1,No,21923.0,3046.0,85520.0,0.0,2.0,Rejected
3,LN1003,NaN,Female,3+,No,19718.0,14947.0,NaN,1.0,0.0,Rejected
4,LN1004,Yes,Female,3+,Yes,9636.0,319.0,299794.0,0.0,0.0,Rejected
...,...,...,...,...,...,...,...,...,...,...,...
613,LN1613,No,Female,2,Yes,4372.0,11822.0,86905.0,0.0,1.0,Approved
614,LN1614,No,Female,2,Yes,3614.0,6723.0,132014.0,1.0,2.0,Rejected
615,LN1615,Yes,Male,1,Yes,14451.0,12379.0,439022.0,1.0,0.0,Rejected
616,LN1616,No,Female,1,No,15067.0,3499.0,169017.0,0.0,2.0,Approved
617,LN1617,No,Female,2,No,7912.0,10428.0,379816.0,1.0,0.0,Rejected